# Generated by Django 5.1.7 on 2025-03-12 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('numero_telefonico', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('rol_usuario', models.CharField(choices=[('admin_general', 'Administrador General'), ('usuario', 'Usuario')], max_length=60)),
                ('contrato_asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_desvinculacion', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_estandar', models.CharField(max_length=20, unique=True, verbose_name='TAG Estándar')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='base.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='RaspadorChancado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='TAG del Raspador')),
                ('raspador', models.CharField(max_length=50, verbose_name='Tipo de Raspador')),
                ('dias_vida_util_disponible', models.IntegerField(verbose_name='Días de Vida Útil Disponible')),
                ('porcentaje_vida_util_disponible', models.FloatField(verbose_name='% de Vida Útil Disponible')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción Recomendada')),
                ('estatus', models.CharField(max_length=50, verbose_name='Estado del Raspador')),
                ('fecha_ultimo_cambio', models.DateField(verbose_name='Fecha Último Cambio')),
                ('ciclo_hoja', models.IntegerField(verbose_name='Ciclo de la Hoja (Días de Operación)')),
                ('proximo_cambio', models.DateField(verbose_name='Fecha Próximo Cambio')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raspadores', to='base.equipo')),
            ],
        ),
    ]
